import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './ui/compoents'
import {Providers} from "./providers";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Golden Morning Events',
  description: 'Generated by create next app', //TODO: Add metadata.
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={inter.className}>
        <Providers>
          <Header/>
          <main className='flex justify-center mb-10'>
            <div className="min-h-screen max-w-5xl mx-4">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
