# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0738a8f084f9b87675c2decf0ce4f1a"
name = "the-hahn-house-website"
application_url = "https://vienna-brandon-warranty-porcelain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "the-hahn-house-marketplace.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vienna-brandon-warranty-porcelain.trycloudflare.com/auth/callback",
  "https://vienna-brandon-warranty-porcelain.trycloudflare.com/auth/shopify/callback",
  "https://vienna-brandon-warranty-porcelain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
